version: '3.8'

networks:
  net:

services:
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF
    volumes:
      - /mnt/nextcloud/database/:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mlp09okn
      - MYSQL_PASSWORD=_db_password_
      - MYSQL_DATABASE=_db_username_
      - MYSQL_USER=nextcloud
    networks:
      - net

  app:
    image: nextcloud
    container_name: nextcolud_app
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /mnt/nextcloud/application:/var/www/html:z
    environment:
      - MYSQL_PASSWORD=_db_password_
      - MYSQL_DATABASE=_db_username_
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - net
